### ISSUE TITLE
wrong font path on Linux Mint 18.2

### ISSUE THREAD

**Issue by lysergik** [free-wheeling/freewheeling#11]
Hello, I've installed freewheeling from the universe debian repositry, and when I launch it into a terminal I have this message(sorry for the lenght):

```
FreeWheeling 0.6
May we return to the circle.
....
VIDEO: Loading font main: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf (20 pt)
VIDEO: Couldn't find font file: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf
Did you run 'make install'?`
```

If you have any idea to how I could fix this I would be interested.

**Comment by neuschaefer** [comment]
This line seems to be the culprit:
```
VIDEO: Couldn't find font file: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf
```

This file should be in either `ttf-dejavu-core` or `fonts-dejavu-core`.

**Comment by lysergik** [comment]
Thanks, the problem was the font. But actually it was in /usr/share/fonts/truetype/dejavu  and not ../ttf-dejavu.

**Comment by bill-auger** [comment]
i am re-opening this just to remind me the debian package needs updating - i have been putting it off hoping the debian packager would do it

if you search the source code of this repo you will find that 'dejavu' is not specified anywhere - freewheeling specifies only the 'vera' fonts and installs it to /usr/share/fweelin as part of the package - IIRC debian added a patch that over-rides the freewheeling's font due to their policy for keeping all fonts under /usr/share/fonts  - i think what is happening here is that mint names its font packages differently or puts them in a different directory than debian - there is a commit on the development branch here that should resolve that problem by first searching the debian fonts directory and then falling back on the freewheeling resources

**Comment by derMart** [comment]
I get the exact same error on Ubuntu 16.04

**Comment by bill-auger** [comment]
derMart -

as stated above, the current ubuntu/mint package is broken - to make it work, open a terminal and run this command:
```
$ sed -i 's|ttf-dejavu|dejavu|' ~/.fweelin/graphics.xml
```
