### ISSUE TITLE
remove unused src/elastin/*

### ISSUE THREAD

**Issue by EtherBit** [free-wheeling/freewheeling#14]
Hi,
I was browsing the source code and noticed the elastin folder. From what I can deduce, it is a time-stretcher/pitch-shifter?
what is the Elastin time-stretching and pitch-shifting algo based on? Roland's VP-9000 Variphrase (elastic audio)? If not, what is it based on? Any useful resource?

**Comment by bill-auger** [comment]
it is clearly about time stretching; but honestly i have never looked into it too much - i could find absolutely nothing about it on the web; so i assume it is a library that JP wrote for other purposes and was planning to use in freewheeling

anyways you can also see in the source that it is sourced from only one file, but is not actually used - it should probably just be deleted

  https://github.com/free-wheeling/freewheeling/blob/master/src/fweelin_block.h#L267

if you are interested in the details, the elastin.h is well documented - today, one would probably use something like librubberband rather than rolling their own

**Comment by EtherBit** [comment]
Thanks. Yeah, I was also curious as to why it was never used; I am guessing it was never finished? There are few other libs I thought about: soundtouch & Superpowered (which I used myself). Looks pretty neat though. Would be nice to salvage it by maybe improving it.

**Comment by bill-auger** [comment]
done 7df80f0
