### ISSUE TITLE
no pckeyboard after build on linux laptop

### ISSUE THREAD

**Issue by ogottogott** [free-wheeling/freewheeling#15]
hello 
I was building freewheeling successfully (did not check out all features yet).
Starting with a simple laptop-only setup I missed the promised pckeyboard when toggling around with tab-key. Since the other three variants showed up it took me a while to understand *this* is the error !

I then found line 35 of interfaces.xml :
  

surprise: decommenting that line enabled the pc keyboard ! 

(1) any other (better) way to enable the pc keyboard ?

(2) why disabled by default ?

thanks in advance

**Comment by bill-auger** [comment]
yes, that was pointed out a few months ago in another issue:

https://github.com/free-wheeling/freewheeling/issues/13#issuecomment-441625571

i think that, not only should it be enabled by default, but it should be
the first one presented on startup of a first-time install; because it
is the most intuitive and universal way to get started - i will
probably do that for the next release

as for "why", the last version that JP published (v0.6.1) had several
new features, some complete, and others still in progress - one of them
was support for the 'BCF-2000' device; which was done in 2009 - he then
took some time off from freewheeling during 2009-2010 then resumed
work on the remaining features that he had planned for v0.6.1 and
released it 2011 - presumably, what happened was that the 'pckeyboard'
interface was disabled for testing purposes; and JP forgot to re-enable
it, or had planned to before releasing v0.6.2

in any case, the XML files are intended to be customized by the user,
and they are explained comprehensively on the wiki:

https://github.com/free-wheeling/freewheeling/wiki/XML-Configuration-System

and also in the config-help.txt file:

~/.fweelin/config-help.txt

the XML Configuration System is perhaps not the most user-friendly for
non-techies, but it is currently the only way to customize without
digging into the source code and recompiling - OTOH, it is very
powerful and can accomplish most of what any user would want to
customize, that most other programs would require modifying the source
code to accomplish

**Comment by bill-auger** [comment]
done 00323c2

the 'pckeyboard' interface is not the default on first run
