### ISSUE TITLE
ubuntu 20.04 - will not start - Can't start video handler!

### ISSUE THREAD

**Issue by s-light** [free-wheeling/freewheeling#25]
i just installed freewheeling from the git sources - 
i run 
```
autoreconf -ivf
./configure
make
sudo make install
```
that was all fine - 

but on start it crashes:
```
FreeWheeling 0.6.6
May we return to the circle.
MEMMGR: Stacksize: 131072.
CORE: Register ringbuffer writer thread: 140706348095232
CORE: RingBuffer 0x55f2caba4e60: Update reader and writer threads to 2
MEM: Memory manager thread (p0)
CONFIG: Starting with 1024 triggers.
CONFIG: Starting with 100 max snapshots.
CONFIG: Library path: 'fw-lib'
CONFIG: Config sets 4 MIDI outputs.
CONFIG: Set 1 MIDI sync outputs: 1 
CONFIG: Starting with 4 external audio input(s)
        and 1 internal audio input(s)--
CONFIG: Input #1 is mono
CONFIG: Input #2 is mono
CONFIG: Input #3 is stereo
CONFIG: Input #4 is stereo
CONFIG: Input #1 is not monitored
CONFIG: Input #2 is not monitored
CONFIG: Input #3 is not monitored
CONFIG: Input #4 is not monitored
CONFIG: Input #1 is not streamed
CONFIG: Input #2 is streamed
CONFIG: Input #3 is streamed
CONFIG: Input #4 is not streamed
CONFIG: Disable final stream
CONFIG: Enable loop stream
CONFIG: No maximum play volume set! Watch your levels!
CONFIG: Maximum limiter gain set to 100.00%.
CONFIG: Limiter threshhold set to 75.00%.
CONFIG: Limiter release rate set to 0.00%.
CONFIG: Fader max dB set to 6.00.
CONFIG: Loop out format is: ogg
CONFIG: Stream out format is: ogg
CONFIG: OGG Quality: 0.500000
CONFIG: FluidSynth running in stereo
CONFIG: FreeWheeling is running in stereo.
        * Please be aware, this significantly increases memory usage. *
CONFIG: Starting with (640,480) resolution.
CONFIG: Video delay: 40 ms
CONFIG: New onscreen font: main: truetype/ttf-bitstream-vera/VeraBd.ttf (20 pt)
CONFIG: New onscreen font: help: truetype/ttf-bitstream-vera/Vera.ttf (16 pt)
CONFIG: New onscreen font: small: truetype/ttf-bitstream-vera/VeraBd.ttf (14 pt)
CONFIG: New onscreen font: tiny: truetype/ttf-bitstream-vera/Vera.ttf (10 pt)
INIT: Load interface 'coreinterface.xml' [first pass]

...

CONFIG: # of interfaces: 4 switchable / 7 non-switchable
Start event manager.
EVENT: Stacksize: 131072.
CORE: Register ringbuffer writer thread: 140706284033792
CORE: RingBuffer 0x55f2caba4e60: Update reader and writer threads to 3
VIDEO: Starting handler..
VIDEO: Stacksize: 131072.
VIDEO: (start) pthread_create failed, exitingMAIN: ERROR: Can't start video handler!
Error starting FreeWheeling!
```

is it expected that the master/main github branch does not start on an kubuntu 20.04?
(i have a new - one year old - laptop - just if this makes any differences) 

the packaged version is currently not available for this os-version..

**Comment by bill-auger** [comment]
FWIW, the program is not "crashing" - it is exiting gracefully due to an exceptional situation, as well-designed software should :)

are you using wayland ?

**Comment by s-light** [comment]
that is my *system information* from the KDE GUI
as i use the Kubuntu variation iam using an KDE desktop - i think this is called `Plasma` 
(but iam not 100% sure on the what is what / naming...)
```
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-67-generic
OS Type: 64-bit
Processors: 16 × Intel® Core™ i9-9980HK CPU @ 2.40GHz
Memory: 31,2 GiB of RAM
```

**Comment by bill-auger** [comment]
i think i found your problem - the error message is misleading -
the pthread library will not initialize due to lacking permission
- after adding the unprivileged user to the 'audio' group, the
program starts

also, if you do not want to compile from source, there is a
package for ubuntu20 in the freewheeling OBS repo

https://software.opensuse.org//download.html?project=home%3Abill-auger&package=freewheeling

if you use the "Add repository and install manually" method, you
would get upgrades automatically with `apt upgarde`

**Comment by bill-auger** [comment]
i think i found your problem - the error message is misleading -
the pthread library will not initialize due to lacking permission -
the program starts as expected, if the user is in the 'audio' group
```
sudo usermod -a -G audio <YOUR_USERNAME>
sudo reboot
```
also, if you do not want to compile from source, there is a
package for ubuntu20 in the freewheeling OBS repo

https://software.opensuse.org//download.html?project=home%3Abill-auger&package=freewheeling

if you use the "Add repository and install manually" method, you
would get upgrades automatically with `apt upgrade`

**Comment by s-light** [comment]
thanks that fixed it and now it is starting!
(now i have to find time to do the quickstart  learning ;-) )
