### ISSUE TITLE
config doesn't mach version.

### ISSUE THREAD

**Issue by magnetophon** [free-wheeling/freewheeling#9]
When starting `fweelin`, at one point I got this message:`INIT: ERROR: Config file version "0.6.1" does not match FreeWheeling version "0.6.3"!`.
I haven't made a config.

**Comment by bill-auger** [comment]
this is referring to the ~/.fweelin/fweelin.xml file in your $HOME dir - you did not need to create it - it it placed there automatically every time the program is run if it is missing and when the version changes

the only real problem here is that it should not say "ERROR" - it is a only warning even in the worst case

only if the config files can not be restored would this ever be a fatal error - either because the default config files can not be found or if for some reason the .fweelin home dir is not writable
